# Use redis password
# docker-compose -f .\docker-compose.redis.yml up -d
# internal client: redis-cli
# COMMANDS:
# Strings: set {key} {value} / get {key}
# Hashes: hmset {key} {field} {value} / hmget {key} {field} / hgetall {key}
# Lists: lpush {key} {value} / lrange {key} {value}  / rpush {key} {start} {final}
# Sets: sadd {key} {value} / smembers {key} / srem {key} {value}
# Sorted Sets: zadd {key} {score} {value} / zrange {key} {start} {final}

version: '3.1'

services:

  redis-cache:
    image: redis:7.0.2-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - my_redis_cache:/data/db
    command: redis-server
    environment:
      - REDIS_PASSWORD=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      - REDIS_MAXMEMORY=20GB
      - REDIS_MAXMEMORY_SAVE=1gb
      - REDIS_LOGLEVEL=warning
volumes:
  my_redis_cache: