# Use redis password
# docker-compose -f .\docker-compose.redis.yml up -d
version: '3.1'

services:

  redis-cache:
    image: redis:7.0.2-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - my_redis_cache:/data/db
    command: redis-server
    environment:
      - REDIS_PASSWORD=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      - REDIS_MAXMEMORY=20GB
      - REDIS_MAXMEMORY_SAVE=1gb
      - REDIS_LOGLEVEL=warning
volumes:
  my_redis_cache: